lib/events_dashboard_web/router.ex
defmodule EventsDashboardWeb.Router do
  use EventsDashboardWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {EventsDashboardWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EventsDashboardWeb do
    pipe_through :browser

    live "/", PageLive, :index
    live "/events", EventsLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", EventsDashboardWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsDashboardWeb.Telemetry
    end
  end
end

lib/events_dashboard/application.ex
defmodule EventsDashboard.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      EventsDashboard.Repo,
      # Start the Telemetry supervisor
      EventsDashboardWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: EventsDashboard.PubSub},
      # Start the Endpoint (http/https)
      EventsDashboardWeb.Endpoint
      # Start a worker by calling: EventsDashboard.Worker.start_link(arg)
      # {EventsDashboard.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: EventsDashboard.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    EventsDashboardWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/events_dashboard/banking_details.ex
defmodule EventsDashboard.BankingDetails do
  use Ecto.Schema
  import Ecto.Changeset

  schema "banking_details" do
    field :customer_id, :integer
    field :account_number, :integer
  end

  def changeset(struct, params) do
    struct
    |> cast(params, [:account_number, :customer_id])
  end
end

lib/events_dashboard/customer.ex
defmodule EventsDashboard.Customer do
  use Ecto.Schema
  import Ecto.Changeset

  schema "customers" do
    field :name, :string
  end

  def changeset(struct, params) do
    struct
    |> cast(params, [:name])
  end
end

lib/events_dashboard/events.ex
defmodule EventsDashboard.Event do
  use Ecto.Schema
  import Ecto.Changeset

  schema "events" do
    field :order_updated, :boolean, default: false
    field :banking_details_updated, :boolean, default: false
    field :customer_updated, :boolean, default: false
  end

  def changeset(struct, params) do
    struct
    |> cast(params, [:order_updated, :banking_details_updated, :customer_updated])
  end
end

lib/events_dashboard/order.ex
defmodule EventsDashboard.Order do
  use Ecto.Schema
  import Ecto.Changeset

  schema "orders" do
    field :customer_id, :integer
    field :banking_details_id, :integer
  end

  def changeset(struct, params) do
    struct
    |> cast(params, [:customer_id, :banking_details_id])
  end
end

lib/events_dashboard/repo.ex
defmodule EventsDashboard.Repo do
  use Ecto.Repo,
    otp_app: :events_dashboard,
    adapter: Ecto.Adapters.Postgres
end

lib/events_dashboard_web/live/events_live.ex
defmodule EventsDashboardWeb.EventsLive do
  use EventsDashboardWeb, :live_view
  alias EventsDashboard.{Event, Repo}
  alias Phoenix.PubSub
  import Ecto.Changeset, only: [change: 2]
  import Ecto.Query

  def mount(_params, _session, socket) do
    PubSub.subscribe(EventsDashboard.PubSub, "update_all")

    {:ok, assign(socket, events: Event |> order_by([asc: :id]) |> Repo.all)}
  end

  def handle_info({:event_updated, id}, socket) do
    {:noreply, assign(socket, events: Event |> order_by([asc: :id]) |> Repo.all)}
  end

  def handle_event("update_event", %{"id" => id}, socket) do
    event = Repo.get(Event, id)
    Repo.update!(change(event, customer_updated: false, banking_details_updated: false, order_updated: false))

    PubSub.broadcast EventsDashboard.PubSub,  "update_all", {:start_workflow, %{id: id}}
    {:noreply, assign(socket, events: Event |> order_by([asc: :id]) |> Repo.all)}
  end

  def handle_info({:start_workflow, id}, socket) do
    :timer.sleep(1000)
    PubSub.broadcast(EventsDashboard.PubSub,  "update_all", {:update_order, %{id: id.id}})
    PubSub.broadcast(EventsDashboard.PubSub,  "update_all", {:update_banking_details, %{id: id.id}})
    PubSub.broadcast(EventsDashboard.PubSub,  "update_all", {:update_customer, %{id: id.id}})
    {:noreply, assign(socket, events: Event |> order_by([asc: :id]) |> Repo.all )}
  end

  def handle_info({:update_customer, id}, socket) do
    :timer.sleep(1000)
    event = Repo.get(Event, id.id)
    Repo.update!(change(event, customer_updated: true))

    PubSub.broadcast(EventsDashboard.PubSub,  "update_all", {:event_updated, %{id: id.id}})
    {:noreply, assign(socket, events: Event |> order_by([asc: :id]) |> Repo.all)}
  end

  def handle_info({:update_banking_details, id}, socket) do
    :timer.sleep(1000)
    event = Repo.get(Event, id.id)
    Repo.update!(change(event, banking_details_updated: true))

    PubSub.broadcast(EventsDashboard.PubSub,  "update_all", {:event_updated, %{id: id.id}})
    {:noreply, assign(socket, events: Event |> order_by([asc: :id]) |> Repo.all)}
  end

  def handle_info({:update_order, id}, socket) do
    :timer.sleep(1000)
    event = Repo.get(Event, id.id)
    Repo.update!(change(event, order_updated: true))

    PubSub.broadcast(EventsDashboard.PubSub,  "update_all", {:event_updated, %{id: id.id}})
    {:noreply, assign(socket, events: Event |> order_by([asc: :id]) |> Repo.all)}
  end
end

lib/events_dashboard_web/live/page_live.ex
defmodule EventsDashboardWeb.PageLive do
  use EventsDashboardWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: "", results: %{})}
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, results: search(query), query: query)}
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not EventsDashboardWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end
end

lib/events_dashboard_web/views/error_view.ex
defmodule EventsDashboardWeb.ErrorView do
  use EventsDashboardWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/events_dashboard_web/views/layout_view.ex
defmodule EventsDashboardWeb.LayoutView do
  use EventsDashboardWeb, :view
end

lib/events_dashboard_web/live/events_live.html.leex
    <table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Order Updated</th>
          <th>Banking Details Updated</th>
          <th>Customer Updated</th>
          <th>Status</th>
          <th>Rerun</th>
        </tr>
      </thead>
      <tbody>
        <%= for event <- @events do %>
          <tr>
            <td><%= event.id %></td>
            <td><%= event.order_updated %></td>
            <td><%= event.banking_details_updated %></td>
            <td><%= event.customer_updated %></td>
             <%= if event.order_updated && event.banking_details_updated && event.customer_updated do %>
            <td> ✅ </td>
            <% else %>
            <td> ❌ </td>
            <%end %>
            <td >  
             <button phx-click="update_event" phx-value-id="<%= event.id %>">Update</button>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

lib/events_dashboard_web/live/page_live.html.leex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace-of-mind from prototype to production</p>

  <form phx-change="suggest" phx-submit="search">
    <input type="text" name="q" value="<%= @query %>" placeholder="Live dependency search" list="results" autocomplete="off"/>
    <datalist id="results">
      <%= for {app, _vsn} <- @results do %>
        <option value="<%= app %>"><%= app %></option>
      <% end %>
    </datalist>
    <button type="submit" phx-disable-with="Searching...">Go to Hexdocs</button>
  </form>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.5/CHANGELOG.md">v1.5 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
    </ul>
  </article>
</section>

lib/events_dashboard_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/events_dashboard_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/events_dashboard_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "EventsDashboard", suffix: " · Phoenix Framework" %>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
            <li><%= link "Live Events", to: Routes.events_path(@conn, :index) %></li>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>